import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../styles/Home.module.css";
import { Card, Row, Col, Container } from "react-bootstrap";
import axios from "axios";
import { Emojione } from "react-emoji-render";

export default function Home(props) {
  return (
    <Container>
      <Head>
        <title>Slack users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{paddingBottom: 50}} className={styles.title}>Slack users list</h1>

        <Row>
            {props.users.map((user) => {
              return (
                <Col xs={4}>
                <Card style={{ width: "18rem" }}>
                  <Card.Img variant="top" src={user.image_512} />
                  <Card.Body>
                    <Card.Title>
                      {user.real_name} <Emojione text={user.status_emoji} />
                    </Card.Title>
                    <Card.Text>
                      <strong>
                        {user.name} {user.status_text}
                      </strong>
                      <p>{user.tz}</p>
                    </Card.Text>
                  </Card.Body>
                </Card>
                </Col>
              );
            })}
        </Row>
      </main>

      <footer className={styles.footer}>
        <p>{new Date().toUTCString()}</p>
      </footer>
    </Container>
  );
}

export async function getServerSideProps(context) {
  const res = await axios.get(`http://localhost:3001/users`);
  const data = res.data;

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { users: data },
  };
}
